### ISSUE TITLE
Detect the Environment Variables

### ISSUE THREAD

**Issue by chenglu** [canonical/flutter-snap#10]
Hi Ken:

There's an [issue](https://github.com/cfug/flutter.cn/issues/708) filed from the Flutter China community:
The Flutter on the Snap store seems ignored the Environment Variables of Flutter: `PUB_HOSTED_URL` and `FLUTTER_STORAGE_BASE_URL`, could you please take a look on this?

Thanks!
cc @InMatrix

**Comment by chenglu** [comment]
any updates on this?

**Comment by MarcusTomlinson** [comment]
Sorry for the delay @chenglu, will look into it tomorrow.

**Comment by chenglu** [comment]
Great, thanks!

**Comment by MarcusTomlinson** [comment]
@chenglu, ok, this is fixed in master now but not published to the snap store just yet. Once published, please run:

```
rm -rf ~/snap/flutter
snap refresh flutter
```

@kenvandine could you trigger a new build of the snap? Thanks!

**Comment by MarcusTomlinson** [comment]
@chenglu this now published :)
