### ISSUE TITLE
When flutter is installed via Snap, there is no flutter/bin in Platform.environment['PATH']] 

### ISSUE THREAD

**Issue by aliyazdi75** [canonical/flutter-snap#12]
https://github.com/flutter/flutter/issues/63325

**Comment by MarcusTomlinson** [comment]
Hi @aliyazdi75, I'm not sure I understand the issue. What is 'flutter/bin' not being in the environment a problem for you?

**Comment by aliyazdi75** [comment]
Hello @MarcusTomlinson,
I have some scripts are using flutter tools like `l10n` and I need the root of `flutter/bin`, there is something code like that I found in `Gallary`, you can see at this [link](https://github.com/flutter/gallery/blob/2f803ebd369e8995aedb6ac1e6cdbb4101864b30/tool/grind.dart#L151 ).

**Comment by MarcusTomlinson** [comment]
@aliyazdi75, I see. ok, I'll look into this tomorrow.

**Comment by MarcusTomlinson** [comment]
@aliyazdi75 ok this is fixed in master now but not published just yet. So sorry this took so long :/

@kenvandine could you please trigger a new build?

**Comment by aliyazdi75** [comment]
Thanks a lot 🙏
