### ISSUE TITLE
Flutter snap does not contain the dart command

### ISSUE THREAD

**Issue by g5becks** [canonical/flutter-snap#13]
Accoring to  https://flutter.dev/docs/get-started/install/linux

> Note: As of Flutter’s 1.19.0 dev release, the Flutter SDK contains the dart command alongside the flutter command so that you can more easily run Dart command-line programs.

Which is true if you install flutter manually, unfortunately, this is not the case when installing flutter via the snap package.

**Comment by MarcusTomlinson** [comment]
Hi @g5becks, thanks for the report. That statement is still true of the snap.

The snap doesn't actually contain the Flutter SDK, it's really just a middleman that installs the SDK for you, and provides the dependancies required to build applications with it.

The SDK is installed to `~/snap/flutter/common/flutter`. There you will find both `dart` and `flutter` commands alongside each other as described in that doc.
