### ISSUE TITLE
GSettings values don't change when running from `flutter run`

### ISSUE THREAD

**Issue by robert-ancell** [canonical/flutter-snap#15]
Steps to reproduce:
1. Run a Flutter app using `flutter run` with an engine that has https://github.com/flutter/engine/pull/22486 applied.
2. Open gnome-control-center
3. Change Accessibility > Large Text setting

Expected result:
Font size in Flutter should change to match setting.

Observed result:
Font size doesn't change. The app is getting GSettings notifications that the value has changed, but when it reads it it always has the same value. If the app binary is directly run the issue doesn't occur.

**Comment by robert-ancell** [comment]
I wonder if the dconf database has been copied into the snap, so the values aren't being modified by external changes. The change events come over D-Bus I think, so these are not affected.

**Comment by seb128** [comment]
The issue is specifics to snaps? Do you use the gsettings interface?

**Comment by robert-ancell** [comment]
The Flutter app is local in this case, i.e. not packaged in a snap. The Flutter snap is classic, so doesn't use any interfaces. @kenvandine - did you have a theory when we discussed this?

**Comment by MarcusTomlinson** [comment]
It’s difficult to diagnose this without a build. @robert-ancell any idea when your PR might land?

**Comment by robert-ancell** [comment]
So I write you a small test app that does it without the PR, and it works. Then I try the PR and it works too. So perhaps something changed that has fixed this? I'll close this but please shout out if anyone sees it again. I'm currently running the flutter snap 0+git.7bbc5b7. Sorry, I didn't record the snap version when I had the issues.

**Comment by MarcusTomlinson** [comment]
Haha. It’s quite possible that I resolved this when pulling some desktop-launch logic into the snap - kinda hoped I had. Good to hear it is fixed :)
