### ISSUE TITLE
issue with bashrc export

### ISSUE THREAD

**Issue by iapicca** [canonical/flutter-snap#22]
## steps to reproduce

- 1 install the latest master 
```
sudo snap install flutter --classic
flutter channel master
flutter upgrade -f
```
- 2 update path in `bashrc`

```bash
export PATH="$PATH:/snap/flutter/common/flutter"
export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"
```

and run `source ~/bashrc`; please note the `.pub-cache/bin`

- 3 run ` flutter pub global activate stagehand`

```bash
Resolving dependencies...
+ args 1.6.0
+ charcode 1.1.3
+ collection 1.14.13
+ http 0.12.2
+ http_parser 3.1.4
+ meta 1.2.4
+ path 1.7.0
+ pedantic 1.9.2
+ source_span 1.7.0
+ stagehand 3.3.11
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ usage 3.4.2
Downloading stagehand 3.3.11...
Precompiling executables...
Precompiled stagehand:stagehand.
Installed executable stagehand.
Warning: Pub installs executables into $HOME/snap/flutter/common/flutter/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"

Activated stagehand 3.3.11.
```

(same result with `flutter pub global activate aqueduct`)

## expected result 

`export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"` should be recognized

 ## actual result 
 
 despite `export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"` being present in `bashrc`
 `flutter`, or rather `dart` inside flutter installation, do not recognize the exported path
 
 ## workaround
 
adding to bashrc `export PATH="$PATH:/snap/flutter/common/flutter/bin/cache/dart-sdk/bin"` 
everything works as intended

 ## doctor
 
 ```console
 [✓] Flutter (Channel master, 1.26.0-2.0.pre.117, on Linux, locale en_US.UTF-8)
    • Flutter version 1.26.0-2.0.pre.117 at /home/francesco/snap/flutter/common/flutter
    • Framework revision 15c009b805 (15 hours ago), 2020-12-22 20:09:03 -0500
    • Engine revision b7cd3f8e70
    • Dart version 2.12.0 (build 2.12.0-173.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.

 ```
 
 ____
 
maybe unrelated, but from the top of my head the cause could be the same that prevent intellij's [dart](https://plugins.jetbrains.com/plugin/6351-dart) and [flutter](https://plugins.jetbrains.com/plugin/9212-flutter) plugins to be recognzed by `flutter doctor -v`

**Comment by MarcusTomlinson** [comment]
Hmm, adding `export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"` to the end of `~/.bashrc` worked fine for me. Did you make sure you restarted the terminal before running the `flutter pub` command?

**Comment by iapicca** [comment]
I did, anyhow I retried  now and somehow it works
I'll close the issue for now

**Comment by ElectroArmy** [comment]
Hi.. I've install Flutter from snap,
when i run flutter doctor -v
![Screenshot from 2021-08-03 17-12-30](https://user-images.githubusercontent.com/39894962/128002793-1bed0077-9bed-4a33-aaac-5af6b2ccfb3d.png)

There is no ANdroid Tool Chain.
 How can i install ?
