### ISSUE TITLE
The dart binary is not exported to the path when installed with snapcraft 

### ISSUE THREAD

**Issue by adnan449** [canonical/flutter-snap#25]
## Steps to Reproduce

Install flutter-sdk with snap on Linux

## Issue

`which dart` will not see any dart binaries in the path

## Expected

The command should return the path to dart: `~/snap/flutter/common/flutter/bin/dart` to confirm it is indeed exported to $PATH

## Suggestion:

Add `~/snap/flutter/common/flutter/bin/dart` to path. I manually added it to `.bashrc`

**Comment by MarcusTomlinson** [comment]
I feel modifying `.bash_rc` on install is a bad idea. Other than that, I can't see how we could "fix" this.

Regardless, I don't think this is within scope of the project. The tool that this snap provides is `flutter`, not `dart`. In fact, all the `dart` operations you'd need in developing a Flutter application can be performed via the `flutter` command anyway right?

What are your thoughts on this @kenvandine?

**Comment by adnan449** [comment]
> Regardless, I don't think this is within scope of the project. The tool that this snap provides is `flutter`, not `dart`.

Do note that recent versions Flutter are expected to provide the users with a Dart SDK. Furthermore there exists no snap package for the Dart SDK at this time.

**Comment by MarcusTomlinson** [comment]
**Update:** We’re just waiting now on the following store request to be approved for this issue to be resolved:

https://forum.snapcraft.io/t/request-for-alias-flutter-dart-dart/22380

**Comment by alexandradeas** [comment]
As mentioned in that link the workaround is alias `flutter.dart` to `dart`. However, this doesn't solve the additional issue of dart tooling expecting other binaries to be included such as `dartfmt` and `dartanalyze` (https://dart.dev/tools/sdk#whats-in-the-dart-sdk). Some tools rely on these being available in the path

**Comment by MarcusTomlinson** [comment]
According to https://dart.dev/tools/dart-tool:

“Before Dart 2.10, the dart command was used only to run the Dart VM. You can still use it that way, but now the command has more functionality. Over time, we expect the dart command to replace most existing commands in the Dart SDK.”

I think it’s fair that we only expose the dart tool by default. If one requires a specialized tool not accessible via dart, I don’t think modifying PATH is too much to ask - as you’re expected to do when manual installing.

**Comment by alexandradeas** [comment]
This goes beyond modifying the path though, what were previously exposed as binaries are now commands to the dart sdk. It's not possible to alias these via snap and also requires knowledge of where a tool is running to determine if it will have access to any shell aliases.

As noted in: https://dart.dev/get-dart
> As of Flutter 1.21, the Flutter SDK includes the full Dart SDK. So if you have Flutter installed, you might not need to explicitly download the Dart SDK.

Dart still bundles the additional utilities as part of its sdk (I'm assuming for the sake of backwards compatibility). If the intention is to bundle the full dart sdk it should also include backwards compatible interfaces for as long as they are maintained by the core dart team

**Comment by MarcusTomlinson** [comment]
> what were previously exposed as binaries are now commands to the dart binary.

This is what I'm saying - if calling `dart` calls the Dart tool from within the Flutter SDK, what else do you need? The rest is just arguments to that command, no need for more aliases.

_If_ the Dart tool wants to call one of the other tools such as `dartfmt` or `dartanalyze` (which I very much doubt it will), then modifying your PATH will certainly be enough.

**Comment by alexandradeas** [comment]
My point isn't about the dart tool but tooling in the dart ecosystem that still use these binaries, which gives users of this snap 2 options:
1. Install dart manually and potentially have different versions running based on what is calling them
2. Install flutter manually and dart manually to prevent versions getting out of sync

**Comment by MarcusTomlinson** [comment]
This is the way I see it: This snap provides the Flutter SDK. According to the official Flutter install guide the only path you need be concerned with is `[FLUTTER_GIT_DIRECTORY]/flutter/bin` (see: https://flutter.dev/docs/get-started/install/linux#update-your-path).

Within this part is just two binaries: `dart` and `flutter`. This snap will provide access to these binaries via `flutter` and `dart` aliases.

I do understand your concern, and perhaps we will run into the issues you've described. At this time however, I think this solution is more than fair.

**Comment by MarcusTomlinson** [comment]
> **Update:** We’re just waiting now on the following store request to be approved for this issue to be resolved:
> 
> https://forum.snapcraft.io/t/request-for-alias-flutter-dart-dart/22380

This is now live.
