### ISSUE TITLE
Flutter beta build not supported

### ISSUE THREAD

**Issue by ferraridamiano** [canonical/flutter-snap#33]
Few days ago the flutter team announces that flutter for linux is now beta (even in the stable channel we have a snapshot of flutter for linux). But if I try to build my app running `snapcraft` I get this error:

`Issues while validating snapcraft.yaml: The 'apps/converternow/extensions[0]' property does not match the required schema: 'flutter-beta' is not one of ['flutter-dev', 'flutter-master', 'gnome-3-28', 'gnome-3-34', 'gnome-3-38', 'kde-neon', 'ros1-noetic', 'ros2-foxy']`

**Comment by MarcusTomlinson** [comment]
This is now fixed in the snapcraft extension, though not yet promoted to stable.

In the meantime you can access the update via edge like so:

`snap refresh snapcraft --edge`
