### ISSUE TITLE
Plugins with extra libraries as dependencies causes build to fail

### ISSUE THREAD

**Issue by talhabalaj** [canonical/flutter-snap#38]
Hello, 
I'm a contributor of [flutter_secure_storage](https://github.com/mogol/flutter_secure_storage), I added the Linux support to this plugin. I noted that the app build succeeds while using the manual installation of Flutter but fails with the Snap version of flutter, as the snap version of flutter can't access the locally-installed libraries (like `libsecret-dev` used in flutter_secure_storage) as snap is isolated.

What should be the approach for plugin developers to fix this?

**Comment by Saviq** [comment]
Hi @talhabalaj, just use `build-packages:`, as documented here:

https://snapcraft.io/docs/snapcraft-yaml-reference

**Comment by MarcusTomlinson** [comment]
@Saviq I don't think @talhabalaj is building a snap himself, I think he's just referring to building an app using the Flutter snap. If that is the case, something is indeed wrong.

**Comment by talhabalaj** [comment]
@MarcusTomlinson  Yes, building an app using Flutter snap, not building Snap which works with the configuration I have, `build-packages` and `stage-packages` both needed to be set for that. I don't why.

**Comment by talhabalaj** [comment]
Problem started here: mogol/flutter_secure_storage#213

**Comment by MarcusTomlinson** [comment]
Apologies for the delay on this, been catching up on the backlog. I'll try have some answers for you early next week.

**Comment by talhabalaj** [comment]
> Apologies for the delay on this, been catching up on the backlog. I'll try have some answers for you early next week.

No worries.

**Comment by MarcusTomlinson** [comment]
This issue is super weird.

`PkgConfig::LIBSECRET` results in a `-lpkgcfg_lib_LIBSECRET_secret-1-NOTFOUND` linker flag, but use `${LIBSECRET_LIBRARIES}` and all works perfectly with the snap.

I'm trying to wrap my head around why `PkgConfig::` would do this when `pkg_check_modules` is seemingly happy.

<img width="613" alt="Screenshot 2021-03-25 at 12 45 05" src="https://user-images.githubusercontent.com/7335138/112474775-efd82580-8d67-11eb-8329-dcb20e6fceba.png">

**Comment by MarcusTomlinson** [comment]
Ok so it appears this is a bug in CMake 3.10 (installed from 18.04 into the snap). Updating the snap to a `core20` base fixes the issue for me at least.

@talhabalaj could I please ask you to give the new candidate snap a try and let me know if it works for you?

```
snap install flutter --classic
snap refresh flutter --channel candidate/20.04
```

Thank you!

**Comment by talhabalaj** [comment]
Thank you so much for looking into this. I'll surely try this soon and will let you know.
