### ISSUE TITLE
Snap store flutter install not working

### ISSUE THREAD

**Issue by simplytestinglol** [canonical/flutter-snap#41]
I tried to install flutter on Ubuntu later version 20.10 and also on latest version of Linux Lite 5.4.
In both I am getting the same below error when tried to install via snap store i.e., sudo snap install flutter --classic

Then when tried to type flutter and press enter in terminal I get below error..

![image](https://user-images.githubusercontent.com/82199043/114134264-0fa14900-9925-11eb-916a-51fbb815d872.png)

Also when flutter doctor same error.

**Comment by MarcusTomlinson** [comment]
Hmm, appears to work fine on 20.10 for me here. Could you try a completely fresh install like so:

```
rm -rf ~/snap/flutter
sudo snap remove --purge flutter
sudo snap install flutter --classic
flutter doctor
```

**Comment by simplytestinglol** [comment]
Ya tried same error. The only way I could work around was installing via tar.gz file.
And for that also android studio was not detected and this stackoverflow https://stackoverflow.com/questions/63356096/flutter-not-detecting-android-studio/65848802 helped me.

Still snap installation not worked. Tried many times..

**Comment by MarcusTomlinson** [comment]
Could you tell me if the following command works for you:

`curl -s -o releases_linux.json https://storage.googleapis.com/flutter_infra/releases/releases_linux.json`

You should then be left with a `releases_linux.json` file in your current directory.

**Comment by simplytestinglol** [comment]
![image](https://user-images.githubusercontent.com/82199043/114179114-36c73d00-995c-11eb-8dc0-d1945a6495e7.png)
I tried to run the above command. And then run flutter doctor.

**Comment by simplytestinglol** [comment]
![image](https://user-images.githubusercontent.com/82199043/114179373-8148b980-995c-11eb-86c7-2f2635702333.png)
These are the complete things I have done

**Comment by MarcusTomlinson** [comment]
How about: `FLUTTER_STORAGE_BASE_URL=https://storage.googleapis.com flutter doctor`

**Comment by simplytestinglol** [comment]
![Uploading image.png…]()

**Comment by simplytestinglol** [comment]
Day before yesterday it was not working in linuxlite. Yesterday in Ubuntu it was not working.
Even today it was not working as you know.
But when I tried many times again and again uninstalling with those commands you provided and tried to install and run flutter doctor.
At one point it worked lol.
I guess there is some issue with the server.
![image](https://user-images.githubusercontent.com/82199043/114183341-354c4380-9961-11eb-8336-2cefa4306b84.png)

**Comment by MarcusTomlinson** [comment]
Yeah I suspect something was up with hitting the google server from your machine. Glad it's fixed. I've updated the snap to output errors on that initial `curl` attempt to hopefully avoid this sort of confusion in the future.
