### ISSUE TITLE
Snap uses an old version of CMake

### ISSUE THREAD

**Issue by lil5** [canonical/flutter-snap#53]
I have encountered an error where I have needed to add a dependency to my project that depends on CMake.

My Linux mint (20.2) installation includes CMake version `3.16.3`, yet in flutter the dependency in question sees a version of CMake `3.10.2`.

:question: Why is such an old version of CMake used in flutter-snap, while ubuntu's repos have updated to CMake `3.16.3`?

Related issue: https://github.com/objectbox/objectbox-dart/issues/317

---

For any developers currently running into this issue my advice is to follow the manual `tar.gz` installation process on the official flutter documentation.

https://docs.flutter.dev/get-started/install/linux#install-flutter-manually

**Comment by tsinis** [comment]
Same here, it would be nice to have a version of CMake 3.15 or higher, at least on edge. Related Issue: https://github.com/harmonoid/libwinmedia/issues/8

**Comment by lil5** [comment]
Possible duplicate of #45

**Comment by bazookon** [comment]
Hi! , any news? I have the same problem. CMake of core18 is too old, please

**Comment by bazookon** [comment]
I found a solution for build a snap app with snapcraft

edit snapcarft.yaml with:

```
parts:
  cmake:
    source: https://github.com/Kitware/CMake
    source-type: git
    source-depth: 1
    plugin: cmake
    override-build: |
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_STAGE/cmake \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install

  yourapp:
```

**Comment by purencool** [comment]
I raised this issue with the flutter team, and they very kindly pointed me to the Flutter Snap project. I am adding it for transparency and anyone who finds the issue I raised. Flutter plugins are now using newer versions of CMake in their plugins. Please see the attached link from the Flutter issue queue.

https://github.com/flutter/flutter/issues/101726
