### ISSUE TITLE
Flutter failed to create file at "/root/project/.dart_tool/flutter_build/404cb2eab34a8ea848f515d5b143e312/.filecache"

### ISSUE THREAD

**Issue by miDeb** [canonical/flutter-snap#55]
When trying to run `snapcraft` on https://github.com/miDeb/digitales_register, I got an error saying 
`Failed to run 'flutter build linux --release -v -t lib/main.dart' for 'dr': Exited with code 1.`.

When I ran this command manually (using `--debug`) inside the `project/` directory, the error message said:
`Flutter failed to create file at
"/root/project/.dart_tool/flutter_build/404cb2eab34a8ea848f515d5b143e312/.filecache".
[        ]            Please ensure that the SDK and/or project is installed in a location that has read/write permissions for
the current user.`:

I wasn't able to create a minimal, reproducible example, but maybe you have an idea what these errors mean?

**Comment by jpnurmi** [comment]
@miDeb That error looks familiar. Try with `--use-lxd`, it helped here.

**Comment by j0chn1** [comment]
Hey,
I got this exception also. For me it makes no difference if running snapcraft or snapcraft --use-lxd.
In both cases I get that error. 
Running flutter build linux --release -v -t lib/main.dart manually works firn (at least the is nor red output line ;) )

**Comment by miDeb** [comment]
I can confirm that running with `--use-lxd` fixed it for me.

**Comment by kwiatek91** [comment]
Currently, I'm having a similar problem 
When I build my flutter project for Linux using docker  on Mac m1 machine, I have valid build
But when I am using to build Raspberry Pi on the same project to run "flutter build linux" command, I have:
(When I'm using  command "flutter build linux --debug" then I don't have this error but still need release version)

`[  +32 ms] Build process failed
[  +20 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      _runBuild
(package:flutter_tools/src/linux/build_linux.dart:185:5)
           <asynchronous suspension>
           #2      buildLinux
(package:flutter_tools/src/linux/build_linux.dart:77:5)
           <asynchronous suspension>
           #3      BuildLinuxCommand.runCommand
           (package:flutter_tools/src/commands/build_linux.dart:88:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand
(package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
`

**Comment by alihassan143** [comment]
@kenvandine  any solution??

**Comment by kenvandine** [comment]
> Currently, I'm having a similar problem When I build my flutter project for Linux using docker on Mac m1 machine, I have valid build But when I am using to build Raspberry Pi on the same project to run "flutter build linux" command, I have: (When I'm using  command "flutter build linux --debug" then I don't have this error but still need release version)
> 
> ```
> [  +32 ms] Build process failed
> [  +20 ms] 
>            #0      throwToolExit
> (package:flutter_tools/src/base/common.dart:10:3)
>            #1      _runBuild
> (package:flutter_tools/src/linux/build_linux.dart:185:5)
>            <asynchronous suspension>
>            #2      buildLinux
> (package:flutter_tools/src/linux/build_linux.dart:77:5)
>            <asynchronous suspension>
>            #3      BuildLinuxCommand.runCommand
>            (package:flutter_tools/src/commands/build_linux.dart:88:5)
>            <asynchronous suspension>
>            #4      FlutterCommand.run.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command.dart:1140:27)
>            <asynchronous suspension>
>            #5      AppContext.run.<anonymous closure>
>            (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #6      CommandRunner.runCommand
> (package:args/command_runner.dart:209:13)
>            <asynchronous suspension>
>            #7      FlutterCommandRunner.runCommand.<anonymous closure>
>            (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
>            <asynchronous suspension>
>            #8      AppContext.run.<anonymous closure>
>            (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #9      FlutterCommandRunner.runCommand
>            (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
>            <asynchronous suspension>
>            #10     run.<anonymous closure>.<anonymous closure>
>            (package:flutter_tools/runner.dart:62:9)
>            <asynchronous suspension>
>            #11     AppContext.run.<anonymous closure>
>            (package:flutter_tools/src/base/context.dart:150:19)
>            <asynchronous suspension>
>            #12     main (package:flutter_tools/executable.dart:94:3)
>            <asynchronous suspension>
> ```

This doesn't sound related to the original issue, please file a new issue.  When I've seen issues where it builds in debug but not release, it's been an issue with one of the plugins, which is not obvious here.  Just something to check.
