### ISSUE TITLE
Snapcraft builds with the latest flutter snap fail with ownership error

### ISSUE THREAD

**Issue by kenvandine** [canonical/flutter-snap#79]
snapcraft builds with the flutter extension are failing since we promoted flutter from edge to stable today.  During the snapcraft build, the "flutter channel dev" command fails with this error:

 `fatal: unsafe repository ('/root/snap/flutter/common/flutter' is owned by someone else)`

**Comment by jpnurmi** [comment]
https://github.blog/2022-04-12-git-security-vulnerability-announced/
