### ISSUE TITLE
`flutter run` fails to start Flutter renderer on 64-bit Fedora 37 with 32-bit DRI drivers present

### ISSUE THREAD

**Issue by marienz** [canonical/flutter-snap#93]
The example application created by `flutter create` does not work when using `flutter run` on 64-bit Fedora 37 (and that's probably not the only distro affected), but it does work if I build and then run it directly. This is most likely because `LIBGL_DRIVERS_PATH` is misconfigured because of what looks like a typo. I'll send a PR to fix the typo but I'm not sure how to test that this fixes the problem (I'm not at all familiar with Snap), so I'm filing this bug report in parallel just in case.

Versions involved:
```
$ snap list
Name     Version        Rev    Tracking       Publisher      Notes
core     16-2.57.6      14399  latest/stable  canonical✓     core
core18   20221205       2654   latest/stable  canonical✓     base
core20   20221123       1738   latest/stable  canonical✓     base
flutter  0+git.ccbc698  130    latest/stable  flutter-team✓  classic
```

`flutter run` fails to open swrast. If we add `EGL_LOG_LEVEL=debug`, we can see it's trying to load it from snap instead of using the system version:
```
$ EGL_LOG_LEVEL=debug flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
libEGL debug: Found 'LIBGL_ALWAYS_SOFTWARE' set, will use a CPU renderer
libEGL debug: MESA-LOADER: failed to open /swrast_dri.so: /swrast_dri.so: cannot open shared object file: No such file or directory

libEGL debug: MESA-LOADER: failed to open /usr/lib/dri/swrast_dri.so: /usr/lib/dri/swrast_dri.so: wrong ELF class: ELFCLASS32

libEGL debug: MESA-LOADER: failed to open /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: /lib64/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/../../../../lib/x86_64-linux-gnu/librt.so.1)

libEGL debug: MESA-LOADER: failed to open /swrast_dri.so: /swrast_dri.so: cannot open shared object file: No such file or directory

libEGL debug: MESA-LOADER: failed to open /usr/lib/dri/swrast_dri.so: /usr/lib/dri/swrast_dri.so: wrong ELF class: ELFCLASS32

libEGL debug: MESA-LOADER: failed to open /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: /lib64/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/../../../../lib/x86_64-linux-gnu/librt.so.1)

libEGL warning: MESA-LOADER: failed to open swrast: /lib64/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/../../../../lib/x86_64-linux-gnu/librt.so.1) (search paths :/usr/lib/dri:/snap/flutter/current/usr/lib/x86_64-linux-gnu/dri::/usr/lib/dri:/snap/flutter/current/usr/lib/x86_64-linux-gnu/dri:, suffix _dri)

libEGL debug: EGL user error 0x3001 (EGL_NOT_INITIALIZED) in eglInitialize


** (day17:17983): WARNING **: 13:48:27.870: Failed to start Flutter renderer: No GL implementation is available
```

Starting the application directly works, using the system's swrast (it also works without `LIBGL_ALWAYS_SOFTWARE=1`):

```
$ LIBGL_ALWAYS_SOFTWARE=1 EGL_LOG_LEVEL=debug build/linux/x64/debug/bundle/day17
libEGL debug: Found 'LIBGL_ALWAYS_SOFTWARE' set, will use a CPU renderer
libEGL debug: MESA-LOADER: dlopen(/usr/lib64/dri/swrast_dri.so)

libEGL debug: found extension `DRI_Core'
...
```

I assume Flutter is supposed to use the system's `swrast_dri.so`, in which case it failing to load `/snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so` is a red herring and the problem is that it did not search `/usr/lib64/dri`.

It looks like the search path is set up by [this code](https://github.com/canonical/flutter-snap/blob/74565fab3ab516bb6a397230f394b3aac07758e8/env.sh#L23), which contains what I'm pretty sure is a typo or mispaste: `HOST_DRIVERS_PATH="$HOST_DIR_DIRS:$(realpath $d/dri)"` should be appending to `HOST_DRIVERS_PATH` (`HOST_DIR_DIRS` is undefined).

Running that code (with the typo) directly in a shell we end up with a `HOST_DRIVERS_PATH` of `:/usr/lib/dri`, but with the typo fixed we get `:/usr/lib64/dri:/usr/lib64/dri:/usr/lib64/dri:/usr/lib/dri:/usr/lib/dri`. I don't know how to test the actual fix (I assume I'd need to locally build the snap somehow, which I'm sure is possible but I was hoping to spend my afternoon learning Flutter, not Snap...). But if `LIBGL_DRIVERS_PATH` is already set `env.sh` prepends `HOST_DRIVERS_PATH` to it, so I can confirm this works:

```
$ EGL_LOG_LEVEL=debug LIBGL_DRIVERS_PATH=/usr/lib64/dri flutter run -d linux
Launching lib/main.dart on Linux in debug mode...
Building Linux application...
libEGL debug: Found 'LIBGL_ALWAYS_SOFTWARE' set, will use a CPU renderer
libEGL debug: MESA-LOADER: failed to open /swrast_dri.so: /swrast_dri.so: cannot open shared object file: No such file or directory

libEGL debug: MESA-LOADER: failed to open /usr/lib/dri/swrast_dri.so: /usr/lib/dri/swrast_dri.so: wrong ELF class: ELFCLASS32

libEGL debug: MESA-LOADER: failed to open /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: /lib64/libpthread.so.0: version `GLIBC_PRIVATE' not
found (required by /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/../../../../lib/x86_64-linux-gnu/librt.so.1)

libEGL debug: MESA-LOADER: failed to open /swrast_dri.so: /swrast_dri.so: cannot open shared object file: No such file or directory

libEGL debug: MESA-LOADER: failed to open /usr/lib/dri/swrast_dri.so: /usr/lib/dri/swrast_dri.so: wrong ELF class: ELFCLASS32

libEGL debug: MESA-LOADER: failed to open /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so: /lib64/libpthread.so.0: version `GLIBC_PRIVATE' not
found (required by /snap/flutter/current/usr/lib/x86_64-linux-gnu/dri/../../../../lib/x86_64-linux-gnu/librt.so.1)

libEGL debug: MESA-LOADER: dlopen(/usr/lib64/dri/swrast_dri.so)

libEGL debug: found extension `DRI_Core'
...
```

So I think it's the right fix.

Note that the only entries on the correct `HOST_DRIVERS_PATH` are copies of `/usr/lib64/dri` and `/usr/lib/dri`. If `/usr/lib/dri` did not exist (that is: if I did not have the 32-bit DRI drivers installed, only the 64-bit ones), that would mask the problem (because that loop checks the directory exists before appending).

**Comment by eifr** [comment]
Hi, although it fixes the issue, it's been merged for 3 weeks.. is it possible to create a new release to the snap store?

**Comment by kenvandine** [comment]
Please test the version in the candidate channel to confirm the fix.

snap refresh --candidate flutter

Thanks!

**Comment by eifr** [comment]
hi @kenvandine :wave: 
I'm getting `snap "flutter" has no updates available` and `flutter run` gives me:
```bash
ib/x86_64-linux-gnu/dri::/usr/lib/dri:/snap/flutter/current/usr/lib/x86_64-linux-gnu/dri:, suffix _dri)


** (goto:22819): WARNING **: 10:44:25.188: Failed to start Flutter renderer: No GL implementation is available

** (goto:22819): WARNING **: 10:44:26.748: Unable to retrieve framework response: No engine to send to

** (goto:22819): WARNING **: 10:44:27.614: Unable to retrieve framework response: No engine to send to

** (goto:22819): WARNING **: 10:44:32.531: Unable to retrieve framework response: No engine to send to
```

**Comment by marienz** [comment]
```
$ sudo snap refresh --candidate flutter
flutter (candidate) 0+git.ccbc698 from Flutter Team✓ refreshed
```

commit ccbc698 predates the fix / still fails.

```
$ snap info flutter
...
refresh-date: today at 14:08 AEDT
channels:
  latest/stable:    0+git.ccbc698 2022-10-20 (130) 215MB classic
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      0+git.fdc90e7 2023-01-26 (134) 216MB classic
```

I think the fix is still in the edge channel / hasn't propagated to the candidate channel yet?

```
$ sudo snap refresh --edge flutter
flutter (edge) 0+git.fdc90e7 from Flutter Team✓ refreshed
```

fdc90e7 is the fix, and works for me (but I wrote the fix... independent testing would be good).

**Comment by eifr** [comment]
```bash
$ sudo snap refresh --edge flutter
```
works for me as well

**Comment by Ph055a** [comment]
`sudo snap refresh --edge flutter`

I can also confirm that this issue has been fixed for me on Fedora 37 after running the above command.
